spring:
  session:
    store-type: none
  datasource:
    url: jdbc:mysql://localhost:3306/turno
    password: Avaya2000
    username: root
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8080
logging:
  file: Turno.log
security:
  user:
    name: user
    password: 1234

